name: CI Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Run Linter, Formatter, and Build Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run ESLint for code quality
        run: npm run lint:check

      - name: Check code formatting with Prettier
        run: npm run format:check

      - name: Run build test
        run: npm run build